#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Copyright (C) 2026 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>

TS_TOPDIR="${0%/*}/../.."
TS_DESC="options"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_BLOCKDEV"
ts_check_test_command "$TS_HELPER_SYSINFO"

ts_skip_nonroot

RUNS_ON_QEMU="$(ts_runs_on_qemu)"

ts_check_losetup

PAGE_SIZE=$("$TS_HELPER_SYSINFO" pagesize)

# The size unit to init loop devices is hardcoded to Mebibyte
# in tests/functions.sh:ts_device_init().
DEV_SIZE_MEBIBYTES="10"

ts_device_init "${DEV_SIZE_MEBIBYTES}"
DEV="$TS_LODEV"


ts_init_subtest "getsz"
"$TS_CMD_BLOCKDEV" --getsz "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


ts_init_subtest "getsize64"
"$TS_CMD_BLOCKDEV" --getsize64 "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


ts_init_subtest "getss"
"$TS_CMD_BLOCKDEV" --getss "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


ts_init_subtest "getpbsz"
"$TS_CMD_BLOCKDEV" --getpbsz "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
ts_finalize_subtest


ts_init_subtest "set-ro-and-rw"

if "$TS_CMD_BLOCKDEV" --setro "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"; then
    "$TS_CMD_BLOCKDEV" --getro "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"

    if "$TS_CMD_BLOCKDEV" --setrw "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"; then
        "$TS_CMD_BLOCKDEV" --getro "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
    else
        ts_failed_subtest "failed to set device read-write"
    fi
else
    ts_failed_subtest "failed to set device read-only"
fi

ts_finalize_subtest


readahead_subts() {
    local name="$1"
    local ret old new
    local get_opt="get${name}"
    local set_opt="set${name}"
    
    ts_init_subtest "set${name}"

    old="$("$TS_CMD_BLOCKDEV" --"$get_opt" "$DEV" 2>>"$TS_ERRLOG")"
    # Increment by two pages expressed in 512-byte sectors
    new="$(( old + ( PAGE_SIZE / 512 ) * 2 ))"

    if "$TS_CMD_BLOCKDEV" --"$set_opt" "$new" "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"; then
        ret="$("$TS_CMD_BLOCKDEV" --"$get_opt" "$DEV" 2>>"$TS_ERRLOG")"

        if (( old < ret )) && (( new == ret )); then
            # Reset it to the previous readahead setting
            "$TS_CMD_BLOCKDEV" --"$set_opt" "$old" "$DEV" >>"$TS_OUTPUT" 2>>"$TS_ERRLOG"
        else
            ts_logerr "unexpected readahead value: $ret"
            ts_logerr "(new: $new old: $old PAGESIZE: $PAGE_SIZE)"
        fi
    else
        if [ "$RUNS_ON_QEMU" == "1" ] && [ "$name" == "fra" ]; then
            ts_skip_subtest "ioctl command BLKFRA{GET,SET} not supported on QEMU"
        else
            ts_logerr "failed to set readahead value: $new"
            ts_logerr "(old: $old PAGESIZE: $PAGE_SIZE)"
        fi
    fi

    ts_finalize_subtest

}

# BLKFRASET (--setfra) and BLKRASET (--setra) are synonymous in the kernel
# but let's stay consistent and test both still.
readahead_subts "ra"
readahead_subts "fra"


ts_finalize
